import matplotlib.pyplot as plt

### set styles
FINAL_PLOT_PARAMS = {
    "figure.facecolor": "white",
    "axes.facecolor": "white",
    "axes.grid": True,
    "axes.grid.axis": "both",
    "grid.color": "#758D99",
    "grid.linewidth": 0.5,
    "axes.spines.left": True,
    "axes.spines.right": False,
    "axes.spines.top": False,
    "axes.spines.bottom": False,
    "ytick.major.size": 0,
    "ytick.minor.size": 0,
    "xtick.direction": "out",
    "xtick.major.size": 5,
    "xtick.color": "#333333",
    "ytick.color": "#333333",
    "axes.edgecolor": "#333333",
    "axes.labelcolor": "#333333",
    "axes.prop_cycle": plt.cycler(
        "color",
        [
            "#DB444B",
            "#006BA2",
            "#3EBCD2",
            "#379A8B",
            "#EBB434",
            "#B4BA39",
            "#9A607F",
            "#D1B07C",
        ],
    ),
    "font.family": "sans-serif",
    # "font.sans-serif": "Roboto",
    "font.sans-serif": "Arial",
    "font.weight": "bold",
    "axes.labelweight": "bold",
    "axes.labelsize": 12,
    "xtick.labelsize": 10,
    "ytick.labelsize": 10,
    # "legend.frameon": True,
    # "legend.framealpha": 1,
    # "legend.edgecolor": "white",
    # "legend.facecolor": "white",
    # "legend.fontsize": 10,
    # "legend.title_fontsize": 11,
}

PLOT_PARAMS = {
    "figure.facecolor": "white",
    "axes.facecolor": "white",
    "axes.grid": True,
    "axes.grid.axis": "both",
    "grid.color": "#758D99",
    "grid.linewidth": 0.5,
    "axes.spines.left": True,
    "axes.spines.right": False,
    "axes.spines.top": False,
    "axes.spines.bottom": False,
    "ytick.major.size": 0,
    "ytick.minor.size": 0,
    "xtick.direction": "out",
    "xtick.major.size": 5,
    "xtick.color": "#333333",
    "ytick.color": "#333333",
    "axes.edgecolor": "#333333",
    "axes.labelcolor": "#333333",
    "axes.prop_cycle": plt.cycler(
        "color",
        [
            "#DB444B",
            "#006BA2",
            "#3EBCD2",
            "#379A8B",
            "#EBB434",
            "#B4BA39",
            "#9A607F",
            "#D1B07C",
        ],
    ),
    "font.family": "sans-serif",
    # "font.sans-serif": "Roboto",
    "font.sans-serif": "Arial",
    "font.weight": "bold",
    "axes.labelweight": "bold",
    "axes.labelsize": 12,
    "xtick.labelsize": 10,
    "ytick.labelsize": 10,
    # "legend.frameon": True,
    # "legend.framealpha": 1,
    # "legend.edgecolor": "white",
    # "legend.facecolor": "white",
    # "legend.fontsize": 10,
    # "legend.title_fontsize": 11,
}
